const esc=(v)=>String(v??'').replace(/[&<>"']/g,ch=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[ch]));
const icon=(name)=>`<i class="fa-solid ${name}" aria-hidden="true"></i>`;
const statusLabel={compatible:'Compatible','compatible-with-upgrade':'Upgrade available','unknown':'Unknown','review-required':'Review required','migration-required':'Migration required',incompatible:'Incompatible','not-applicable':'N/A'};
const statusIcon={compatible:'fa-circle-check','compatible-with-upgrade':'fa-arrow-up-right-dots',unknown:'fa-circle-question','review-required':'fa-magnifying-glass','migration-required':'fa-route',incompatible:'fa-circle-xmark','not-applicable':'fa-minus'};
function badge(s){return `<span class="compat-status compat-status--${esc(s)}">${icon(statusIcon[s]??'fa-circle')} ${esc(statusLabel[s]??s)}</span>`;}
function supportBadge(s){return `<span class="compat-support">${esc(String(s??'').replaceAll('-',' '))}</span>`;}
function header(title,desc,engine){return `<div class="page-header"><div><span class="page-eyebrow">Lifecycle</span><h1>${esc(title)}</h1><p>${esc(desc)}</p></div><div class="header-actions"><span class="status-badge status-badge--stable">v${esc(engine.currentVersion)}</span><a class="button button--secondary button--compact" href="./standards/34-compatibility-center-standard.md"><i class="fa-solid fa-file-lines" aria-hidden="true"></i> Standard</a></div></div>`;}
function nav(view){const items=[['overview','Overview','fa-grid-2'],['releases','Release readiness','fa-tags'],['surfaces','Platform surfaces','fa-layer-group'],['sites','Reference Sites','fa-window-maximize'],['definitions','Definitions','fa-database']];return `<nav class="compat-tabs" aria-label="Compatibility Center views">${items.map(([id,label,ic])=>`<a href="#/lifecycle/compatibility${id==='overview'?'':`?view=${id}`}" class="compat-tab ${view===id?'is-active':''}" ${view===id?'aria-current="page"':''}>${icon(ic)} ${label}</a>`).join('')}</nav>`;}
function metric(label,value,caption,ic){return `<article class="paper-card compat-metric"><span class="compat-metric__icon">${icon(ic)}</span><div><span>${esc(label)}</span><strong>${esc(value)}</strong><small>${esc(caption)}</small></div></article>`;}

function overview(engine){
 const current=engine.release(engine.currentVersion);const exact=engine.releases.filter(x=>x.exactSnapshotAvailable).length;const ref=engine.referenceSites.length;const api=engine.components.filter(x=>x.componentType==='api-group').length;const runtime=engine.components.find(x=>x.componentId==='site-runtime');
 return `<div class="stack stack--lg">
  <section class="compat-callout"><span>${icon('fa-shield-halved')}</span><div><h2>Compatibility is evidence, not a deployment approval</h2><p>The Center combines exact release history, Contract Diff, Site Manifest declarations and canonical platform registries. It never modifies a Site, migrates data or fabricates missing runtime support.</p></div></section>
  <div class="compat-metrics">${metric('Target Contract',`v${engine.currentVersion}`,'Current coordinated Registry release','fa-code-branch')}${metric('Exact release history',String(exact),`${engine.releases.length} release descriptors total`,'fa-box-archive')}${metric('API contract surfaces',String(api),'Each versioned independently','fa-code')}${metric('Reference Sites',String(ref),'Repository examples only','fa-flask')}</div>
  <div class="compat-two-col">
   <article class="paper-card"><div class="paper-card__header"><div><h2>Current support truth</h2><p>Whole-platform support posture is deliberately separate from individual contract lifecycle status.</p></div>${supportBadge(current?.supportLevel??'current-development')}</div><div class="paper-card__body">
    <div class="compat-support-truth"><span>${icon('fa-flask')}</span><div><strong>Pre-1.0 development foundation train</strong><p>V0.x releases are contract-development baselines. The registry does not claim a production support train before explicit V1.0.0 Production Acceptance.</p></div></div>
    <dl class="data-list"><div class="data-list__row"><dt>Current release</dt><dd><code>${esc(engine.currentVersion)}</code></dd></div><div class="data-list__row"><dt>Production eligible</dt><dd>No, not until formal V1.0.0 acceptance</dd></div><div class="data-list__row"><dt>Exact current snapshot</dt><dd>${current?.exactSnapshotAvailable?'Available':'Unavailable'}</dd></div><div class="data-list__row"><dt>Automatic upgrades</dt><dd>Never</dd></div></dl>
   </div></article>
   <article class="paper-card"><div class="paper-card__header"><div><h2>Compatibility dimensions</h2><p>A Site is assessed across independent required and optional surfaces.</p></div><span class="tag">${engine.dimensions.length} dimensions</span></div><div class="paper-card__body compat-dimension-list">${engine.dimensions.map(d=>`<div><span>${icon(d.required?'fa-circle-check':'fa-circle-dot')}</span><div><strong>${esc(d.label)}</strong><small>${d.required?'Required dimension':'Conditional/optional dimension'}</small></div></div>`).join('')}</div></article>
  </div>
  <div class="compat-two-col">
   <article class="paper-card"><div class="paper-card__header"><div><h2>Site Runtime / SDK</h2><p>Contract existence and runtime implementation are different facts.</p></div>${badge(runtime?.compatibilityStatus??'unknown')}</div><div class="paper-card__body"><p>${esc(runtime?.summary??'No runtime declaration available.')}</p><div class="compat-note">${icon('fa-circle-info')} A future runtime release must declare exact supported Contract, Manifest and API versions before this dimension can become a runtime compatibility pass.</div></div></article>
   <article class="paper-card"><div class="paper-card__header"><div><h2>Upgrade workflow</h2><p>Required before a pinned Contract Version changes.</p></div><a class="button button--secondary button--compact" href="#/lifecycle/diff"><i class="fa-solid fa-code-compare" aria-hidden="true"></i> Contract Diff</a></div><div class="paper-card__body"><ol class="compat-steps"><li>Read the Site Manifest.</li><li>Review release readiness and exact Diff.</li><li>Resolve affected Modules, APIs, Permissions, Events and Integrations.</li><li>Prepare migration/review work.</li><li>Validate target declaration.</li><li>Update the version pin explicitly.</li></ol></div></article>
  </div>
 </div>`;
}
function releases(engine,f){const rows=engine.searchReleases(f.q,f.status);return `<div class="stack stack--lg"><section class="paper-card"><div class="paper-card__header"><div><h2>Release readiness to v${esc(engine.currentVersion)}</h2><p>Release-level compatibility is derived from exact Contract Diff evidence where available.</p></div><span class="tag">${rows.length} shown</span></div><div class="paper-card__body compat-filter-row"><label class="field field--search"><span>Search release</span><input type="search" value="${esc(f.q)}" placeholder="0.23.0 or migration" data-compat-q></label><label class="field"><span>Status</span><select data-compat-status><option value="">All statuses</option>${engine.statuses.map(x=>`<option value="${esc(x.id)}" ${f.status===x.id?'selected':''}>${esc(x.label)}</option>`).join('')}</select></label><button class="button button--ghost" type="button" data-compat-clear>Clear</button></div><div class="compat-table-wrap" data-compat-results>${releaseTable(engine,rows)}</div></section></div>`;}
function releaseTable(engine,rows){if(!rows.length)return `<div class="compat-empty"><h3>No releases match</h3><p>Change the search or status filter.</p></div>`;return `<table class="compat-table"><thead><tr><th>Release</th><th>Evidence</th><th>Support</th><th>Compatibility to ${esc(engine.currentVersion)}</th><th>Change evidence</th><th></th></tr></thead><tbody>${rows.map(r=>`<tr><td><strong>v${esc(r.version)}</strong><small>Phase ${esc(r.phase??'—')}</small></td><td>${r.exactSnapshotAvailable?'<span class="compat-evidence compat-evidence--exact">Exact snapshot</span>':'<span class="compat-evidence">Unavailable</span>'}</td><td>${supportBadge(r.supportLevel)}</td><td>${badge(r.compatibilityStatus)}<small>${esc(r.summary)}</small></td><td><span>${esc(r.changeSummary??'No exact comparison')}</span></td><td>${r.exactSnapshotAvailable&&r.version!==engine.currentVersion?`<a class="icon-button" href="#/lifecycle/diff?from=${encodeURIComponent(r.version)}&to=${encodeURIComponent(engine.currentVersion)}" aria-label="Compare ${esc(r.version)} to ${esc(engine.currentVersion)}"><i class="fa-solid fa-code-compare" aria-hidden="true"></i></a>`:''}</td></tr>`).join('')}</tbody></table>`;}
function surfaces(engine,f){const types=[...new Set(engine.components.map(x=>x.componentType))].sort();const rows=engine.searchComponents(f.q,f.status,f.type);return `<div class="stack stack--lg"><section class="paper-card"><div class="paper-card__header"><div><h2>Platform surface matrix</h2><p>Shows specification presence separately from runtime implementation.</p></div><span class="tag">${rows.length} shown</span></div><div class="paper-card__body compat-filter-row"><label class="field field--search"><span>Search surface</span><input type="search" value="${esc(f.q)}" placeholder="API, runtime, manifest..." data-compat-q></label><label class="field"><span>Status</span><select data-compat-status><option value="">All statuses</option>${engine.statuses.map(x=>`<option value="${esc(x.id)}" ${f.status===x.id?'selected':''}>${esc(x.label)}</option>`).join('')}</select></label><label class="field"><span>Type</span><select data-compat-type><option value="">All types</option>${types.map(x=>`<option value="${esc(x)}" ${f.type===x?'selected':''}>${esc(x.replaceAll('-',' '))}</option>`).join('')}</select></label><button class="button button--ghost" type="button" data-compat-clear>Clear</button></div><div class="compat-surface-grid" data-compat-results>${surfaceCards(rows)}</div></section></div>`;}
function surfaceCards(rows){if(!rows.length)return `<div class="compat-empty"><h3>No surfaces match</h3></div>`;return rows.map(x=>`<article class="compat-surface"><div class="compat-surface__top"><div><span class="tag">${esc(x.componentType.replaceAll('-',' '))}</span><h3>${esc(x.name)}</h3><code>${esc(x.componentId)}</code></div>${badge(x.compatibilityStatus)}</div><dl><div><dt>Specification/API version</dt><dd>${x.specificationVersion?`<code>${esc(x.specificationVersion)}</code>`:'Not declared'}</dd></div><div><dt>Registry release</dt><dd>${x.registryRelease?`v${esc(x.registryRelease)}`:'—'}</dd></div><div><dt>Runtime implementation</dt><dd>${x.runtimeImplemented?'Declared':'Not declared'}</dd></div></dl><p>${esc(x.summary)}</p>${x.source?`<a href="./${esc(x.source)}" class="compat-source"><i class="fa-solid fa-file-lines" aria-hidden="true"></i> Source</a>`:''}</article>`).join('');}
function sites(engine,f){const rows=engine.searchSites(f.q,f.status);return `<div class="stack stack--lg"><section class="compat-callout compat-callout--info"><span>${icon('fa-flask')}</span><div><h2>Reference data only</h2><p>These assessments use the non-secret example manifests bundled in this repository. They do not represent a real customer deployment or runtime health check.</p></div></section><section class="paper-card"><div class="paper-card__header"><div><h2>Reference Site readiness</h2><p>Manifest-aware compatibility against the current target release.</p></div><span class="tag">${rows.length} shown</span></div><div class="paper-card__body compat-filter-row"><label class="field field--search"><span>Search Site type</span><input type="search" value="${esc(f.q)}" placeholder="commerce, corporate..." data-compat-q></label><label class="field"><span>Status</span><select data-compat-status><option value="">All statuses</option>${engine.statuses.map(x=>`<option value="${esc(x.id)}" ${f.status===x.id?'selected':''}>${esc(x.label)}</option>`).join('')}</select></label><button class="button button--ghost" type="button" data-compat-clear>Clear</button></div><div class="compat-site-grid" data-compat-results>${siteCards(rows)}</div></section></div>`;}
function siteCards(rows){if(!rows.length)return `<div class="compat-empty"><h3>No reference assessments match</h3></div>`;return rows.map(x=>`<article class="compat-site"><div class="compat-site__head"><div><span class="tag">${esc(x.siteType)}</span><h3>${esc(x.name)}</h3><code>${esc(x.id)}</code></div>${badge(x.overallStatus)}</div><div class="compat-version-flow"><span>v${esc(x.sourceContractVersion)}</span><i class="fa-solid fa-arrow-right" aria-hidden="true"></i><strong>v${esc(x.targetContractVersion)}</strong></div><p>${esc(x.summary)}</p><div class="compat-site__dims">${(x.dimensions??[]).map(d=>`<span title="${esc(d.summary??'')}">${esc(d.dimension)} ${badge(d.status)}</span>`).join('')}</div><div class="compat-site__actions"><a class="button button--secondary button--compact" href="${esc(x.manifestRoute)}"><i class="fa-solid fa-file-code" aria-hidden="true"></i> Manifest</a>${x.diffRoute?`<a class="button button--secondary button--compact" href="${esc(x.diffRoute)}"><i class="fa-solid fa-code-compare" aria-hidden="true"></i> Diff</a>`:''}</div></article>`).join('');}
function definitions(engine){return `<div class="stack stack--lg"><section class="paper-card"><div class="paper-card__header"><div><h2>Compatibility definitions</h2><p>Machine-readable schemas, vocabularies, matrices and policies indexed by NEXT F Contracts.</p></div><span class="tag">${engine.definitions.length} support schemas</span></div><div class="compat-def-grid">${engine.definitions.map(x=>`<a class="compat-def" href="#/registry/item/${encodeURIComponent(x.$id)}"><span>${icon('fa-cube')}</span><div><strong>${esc(x.name)}</strong><code>${esc(x.$id)}</code><p>${esc(x.description)}</p></div><i class="fa-solid fa-chevron-right" aria-hidden="true"></i></a>`).join('')}</div></section><section class="paper-card"><div class="paper-card__header"><div><h2>Authoritative source set</h2><p>Compatibility Center data remains version-controlled and machine-readable.</p></div></div><div class="paper-card__body"><dl class="data-list"><div class="data-list__row"><dt>Operational standard</dt><dd><a href="./standards/34-compatibility-center-standard.md">standards/34-compatibility-center-standard.md</a></dd></div><div class="data-list__row"><dt>Baseline policy</dt><dd><a href="./standards/07-compatibility-policy.md">standards/07-compatibility-policy.md</a></dd></div><div class="data-list__row"><dt>Registry index</dt><dd><a href="./registry/compatibility/index.json">registry/compatibility/index.json</a></dd></div><div class="data-list__row"><dt>Release matrix</dt><dd><a href="./registry/compatibility/release-compatibility.json">registry/compatibility/release-compatibility.json</a></dd></div><div class="data-list__row"><dt>Surface matrix</dt><dd><a href="./registry/compatibility/component-matrix.json">registry/compatibility/component-matrix.json</a></dd></div></dl></div></section></div>`;}
export function renderCompatibilityPage(engine,filters){const view=filters.view??'overview';let body=view==='releases'?releases(engine,filters):view==='surfaces'?surfaces(engine,filters):view==='sites'?sites(engine,filters):view==='definitions'?definitions(engine):overview(engine);return `${header('Compatibility Center','Assess exact release readiness, platform surfaces and reference Site declarations without changing a Site.',engine)}${nav(view)}${body}`;}
export function renderCompatibilityResults(engine,filters){return filters.view==='releases'?releaseTable(engine,engine.searchReleases(filters.q,filters.status)):filters.view==='surfaces'?surfaceCards(engine.searchComponents(filters.q,filters.status,filters.type)):filters.view==='sites'?siteCards(engine.searchSites(filters.q,filters.status)):'';}
