const e=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const badge=(text,cls='stable')=>`<span class="status-badge status-badge--${cls}">${e(text)}</span>`;
const header=(title,desc,actions='')=>`<header class="page-header"><div><div class="eyebrow">Events</div><h1>${e(title)}</h1><p>${e(desc)}</p></div>${actions}</header>`;
const link=id=>`<a class="contract-link" href="#/registry/item/${encodeURIComponent(id)}"><code>${e(id)}</code></a>`;
const source=path=>`<a class="button button--ghost button--compact" href="./${e(path)}" target="_blank" rel="noopener"><i class="fa-solid fa-file-code"></i> Source</a>`;
const row=(k,v)=>`<div class="data-list__row"><dt>${e(k)}</dt><dd>${v}</dd></div>`;
function options(items,value,label=x=>x){return items.map(x=>{const v=typeof x==='string'?x:x.key;const l=typeof x==='string'?label(x):(x.label??x.key);return `<option value="${e(v)}" ${v===value?'selected':''}>${e(l)}</option>`}).join('')}
function eventCard(x){return `<article class="event-card"><div class="event-card__top"><div><code class="machine-id">${e(x.eventKey)}</code><h3>${e(x.name)}</h3></div>${badge(x.eventVersion,'stable')}</div><p>${e(x.description)}</p><div class="event-card__meta"><span><i class="fa-solid fa-layer-group"></i>${e(x.category)}</span><span><i class="fa-solid fa-tower-broadcast"></i>${e(x.producerKey)}</span><span><i class="fa-solid fa-shield"></i>${e(x.dataPolicy?.sensitivity??'internal')}</span></div><div class="event-card__footer"><span class="tag">${x.webhookEligible?'Webhook eligible':'Internal only'}</span><a class="button button--ghost button--compact" href="#/registry/item/${encodeURIComponent(x.eventKey)}">Inspect</a></div></article>`}
function schemaCard(x){return `<article class="event-card event-card--schema"><div class="event-card__top"><div><code class="machine-id">${e(x.$id)}</code><h3>${e(x.name)}</h3></div>${badge('Schema','info')}</div><p>${e(x.description)}</p><div class="event-card__footer"><span class="tag">${x.fields?.length??0} fields</span><a class="button button--ghost button--compact" href="#/registry/item/${encodeURIComponent(x.$id)}">Inspect</a></div></article>`}
export function renderEventsResults(engine,f={}){const rows=engine.search(f.q??'',f);if(!rows.length)return `<div class="empty-state"><i class="fa-solid fa-bolt"></i><h3>No matching event contracts</h3><p>Adjust the filters or search by canonical key, producer, subject or consumer.</p></div>`;return `<div class="event-grid">${rows.map(x=>x.eventKey?eventCard(x):schemaCard(x)).join('')}</div>`}
export function renderEventsIndex(engine,f={}){const count=engine.search(f.q??'',f).length;const sensitivities=[...new Set(engine.events.map(x=>x.dataPolicy?.sensitivity).filter(Boolean))].sort();return `${header('Event Registry','Canonical completed-fact events used across NEXT F Sites, CMS, Admin, commerce, integrations and future webhooks.',`<div class="header-actions">${badge('Phase 13')}<span class="tag">${engine.events.length} events</span><span class="tag">${engine.schemas.length} support schemas</span></div>`)}<div class="stack stack--lg event-page">
<div class="registry-source-bar"><span><i class="fa-solid fa-database"></i> Runtime source</span><strong>${e(engine.source)}</strong><span class="tag">v${e(engine.data.registryVersion)}</span></div>
<div class="callout"><span class="callout__icon"><i class="fa-solid fa-circle-info"></i></span><div><h3>Domain events are authoritative facts</h3><p>Phase 13 events are produced after server validation and authoritative state changes. They are not browser tracking pixels, commands or webhooks. Phase 14 will define webhook transport.</p></div></div>
<section class="paper-card"><div class="paper-card__header"><div><h2>Find event contracts</h2><p>Search canonical keys and filter by event semantics.</p></div><button class="button button--ghost button--compact" data-events-clear>Clear</button></div><div class="paper-card__body event-filter-grid">
<label class="field"><span>Search</span><input type="search" value="${e(f.q??'')}" placeholder="order.paid, inventory, consent..." data-events-q></label>
<label class="field"><span>View</span><select data-events-view><option value="all" ${f.view==='all'?'selected':''}>All</option><option value="events" ${f.view==='events'?'selected':''}>Events</option><option value="schemas" ${f.view==='schemas'?'selected':''}>Support schemas</option></select></label>
<label class="field"><span>Category</span><select data-events-category><option value="">All categories</option>${options(engine.categories,f.category)}</select></label>
<label class="field"><span>Producer</span><select data-events-producer><option value="">All producers</option>${options(engine.producers,f.producer)}</select></label>
<label class="field"><span>Sensitivity</span><select data-events-sensitivity><option value="">All</option>${options(sensitivities,f.sensitivity)}</select></label>
<label class="field"><span>Webhook</span><select data-events-webhook><option value="" ${!f.webhook?'selected':''}>All</option><option value="yes" ${f.webhook==='yes'?'selected':''}>Eligible</option><option value="no" ${f.webhook==='no'?'selected':''}>Internal only</option></select></label>
</div><div class="paper-card__footer"><span><strong data-events-count>${count}</strong> definitions shown</span><span>${engine.events.length} canonical events total</span></div></section>
<section data-events-results>${renderEventsResults(engine,f)}</section>
<section class="dashboard-grid dashboard-grid--3"><article class="paper-card"><div class="paper-card__body"><h3>Immutable occurrence</h3><p>Every occurrence has one globally unique event ID. Recorded occurrences cannot be rewritten.</p></div></article><article class="paper-card"><div class="paper-card__body"><h3>Durable production</h3><p>Transactional business facts require a transactional outbox or equivalent durability boundary.</p></div></article><article class="paper-card"><div class="paper-card__body"><h3>Transport independent</h3><p>An event remains the same fact whether later consumed by a queue, API, automation or webhook bridge.</p></div></article></section>
</div>`}
function payloadTable(fields=[]){if(!fields.length)return '<p class="muted">No additional event-specific payload fields. The shared Event Envelope still applies.</p>';return `<div class="table-wrap"><table class="registry-table"><thead><tr><th>Field</th><th>Required</th><th>Type</th><th>Meaning</th></tr></thead><tbody>${fields.map(f=>`<tr><td><code>${e(f.key)}</code></td><td>${f.required?'Yes':'No'}</td><td><code>${e(f.type)}</code></td><td>${e(f.description)}</td></tr>`).join('')}</tbody></table></div>`}
export function renderEventDetail(registry,item,x){return `${header(x.name,x.description,`<div class="header-actions">${badge(x.eventVersion)}${source(item.source)}</div>`)}<div class="stack stack--lg event-detail">
<div class="event-identity"><div><span>Canonical event key</span><code>${e(x.eventKey)}</code></div><button class="button button--ghost button--compact" data-copy-value="${e(x.eventKey)}" data-copy-label="Event key copied"><i class="fa-regular fa-copy"></i> Copy key</button></div>
<div class="dashboard-grid dashboard-grid--3"><article class="paper-card"><div class="paper-card__body"><span class="metric-label">Producer</span><strong>${e(x.producerKey)}</strong><p>${e(x.category)}</p></div></article><article class="paper-card"><div class="paper-card__body"><span class="metric-label">Data</span><strong>${e(x.dataPolicy.sensitivity)}</strong><p>${x.dataPolicy.containsPersonalData?'May contain personal data':'No personal data expected'}${x.dataPolicy.containsFinancialData?' · financial':''}</p></div></article><article class="paper-card"><div class="paper-card__body"><span class="metric-label">Webhook Phase 14</span><strong>${x.webhookEligible?'Eligible':'Not eligible'}</strong><p>Eligibility does not define delivery transport.</p></div></article></div>
<article class="paper-card"><div class="paper-card__header"><div><h2>Exact trigger</h2><p>The authoritative moment this fact exists.</p></div></div><div class="paper-card__body"><p class="event-trigger">${e(x.trigger)}</p></div></article>
<article class="paper-card"><div class="paper-card__header"><div><h2>Subjects & consumers</h2><p>Canonical entity scope and declared consumer classes.</p></div></div><div class="paper-card__body dashboard-grid dashboard-grid--2"><div><h3>Allowed subjects</h3><div class="chip-list">${x.subjectContracts.map(link).join('')}</div></div><div><h3>Consumers</h3><div class="chip-list">${x.consumers.map(c=>`<span class="tag">${e(c)}</span>`).join('')}</div></div></div></article>
<article class="paper-card"><div class="paper-card__header"><div><h2>Event-specific payload</h2><p>Minimum payload in addition to the canonical Event Envelope.</p></div></div><div class="paper-card__body">${payloadTable(x.payloadFields)}</div></article>
<div class="dashboard-grid dashboard-grid--2"><article class="paper-card"><div class="paper-card__header"><div><h2>Production policy</h2></div></div><div class="paper-card__body"><dl class="data-list">${row('Durability',e(x.productionPolicy.durability))}${row('Commit boundary',e(x.productionPolicy.commitBoundary))}${row('Failure behavior',e(x.productionPolicy.failureBehavior))}${row('Ordering scope',e(x.orderingPolicy.scope))}${row('Retention',e(x.retention.class))}</dl></div></article><article class="paper-card"><div class="paper-card__header"><div><h2>Idempotency</h2></div></div><div class="paper-card__body"><dl class="data-list">${row('Dedupe key',e(x.idempotency.dedupeKey))}${row('Command replay',e(x.idempotency.replayedIdempotentCommand))}${row('Consumer idempotency',x.idempotency.consumerIdempotencyRequired?'Required':'Optional')}</dl></div></article></div>
<article class="paper-card"><div class="paper-card__header"><div><h2>Validation rules</h2><p>Required invariants for every implementation.</p></div></div><div class="paper-card__body"><ol class="rule-list">${x.validationRules.map(r=>`<li><code>${e(r.id)}</code><p>${e(r.description)}</p></li>`).join('')}</ol></div></article>
<article class="paper-card"><div class="paper-card__header"><div><h2>Raw authoritative definition</h2></div><button class="button button--ghost button--compact" data-copy-value='${e(JSON.stringify(x))}' data-copy-label="Event JSON copied">Copy JSON</button></div><div class="paper-card__body"><pre class="code-panel"><code>${e(JSON.stringify(x,null,2))}</code></pre></div></article></div>`}
export function renderEventSupportDetail(registry,item,x){return `${header(x.name,x.description,`<div class="header-actions">${badge('Schema','info')}${source(item.source)}</div>`)}<div class="stack stack--lg"><div class="event-identity"><div><span>Schema ID</span><code>${e(x.$id)}</code></div><button class="button button--ghost button--compact" data-copy-value="${e(x.$id)}" data-copy-label="Schema ID copied">Copy ID</button></div><article class="paper-card"><div class="paper-card__header"><div><h2>Fields</h2><p>Reusable Event Registry infrastructure contract.</p></div></div><div class="paper-card__body">${payloadTable((x.fields??[]).map(f=>({key:f.key,required:f.required,type:f.primitive??f.schema??f.itemsPrimitive??f.itemsSchema??'object',description:f.description})))}</div></article><article class="paper-card"><div class="paper-card__header"><div><h2>Validation rules</h2></div></div><div class="paper-card__body"><ol class="rule-list">${(x.validationRules??[]).map(r=>`<li><code>${e(r.id)}</code><p>${e(r.description)}</p></li>`).join('')}</ol></div></article><article class="paper-card"><div class="paper-card__header"><div><h2>Raw authoritative definition</h2></div></div><div class="paper-card__body"><pre class="code-panel"><code>${e(JSON.stringify(x,null,2))}</code></pre></div></article></div>`}
export function renderEventsDetail(registry,item,x){return x?.eventKey?renderEventDetail(registry,item,x):renderEventSupportDetail(registry,item,x)}
