export const routes = [
  { id: "overview", path: "/overview", title: "Overview", group: "Overview", icon: "fa-house", phase: 37, status: "current", description: "Contract portal foundation, authority model and completed V1 Registry roadmap." },
  { id: "global-search", path: "/search", title: "Global Search", group: "Overview", icon: "fa-magnifying-glass", phase: 23, status: "available", description: "Search canonical contracts, fields, Events, Webhooks, Permissions, Modules, APIs, examples, routes and documentation from one local index." },
  { id: "registry-health", path: "/registry/health", title: "Registry Health", group: "Overview", icon: "fa-heart-pulse", phase: 36, status: "available", description: "Repository-wide release-candidate QA, integrity evidence, findings and acceptance status." },

  { id: "standards-architecture", path: "/standards/architecture", title: "Architecture", group: "Standards", icon: "fa-sitemap", phase: 0, status: "available", description: "Core contract boundaries, authority, reuse and platform architecture rules." },
  { id: "standards-naming", path: "/standards/naming", title: "Naming", group: "Standards", icon: "fa-i-cursor", phase: 0, status: "available", description: "Canonical field, contract, event, permission, URL and ID naming rules." },
  { id: "standards-development", path: "/standards/development", title: "Development", group: "Standards", icon: "fa-code", phase: 0, status: "available", description: "Contract-first development and implementation rules for NEXT F projects." },
  { id: "standards-security", path: "/standards/security", title: "Security", group: "Standards", icon: "fa-shield-halved", phase: 29, status: "available", description: "Machine-readable security controls, secrets, browser/API boundaries, verification expectations and cross-registry security mappings." },
  { id: "standards-privacy", path: "/standards/privacy", title: "Privacy & Data", group: "Standards", icon: "fa-user-shield", phase: 30, status: "available", description: "Machine-readable data classification, flow eligibility, retention, consent, redaction and privacy-operation standards." },
  { id: "standards-accessibility", path: "/standards/accessibility", title: "Accessibility", group: "Standards", icon: "fa-universal-access", phase: 31, status: "available", description: "Machine-readable accessibility controls, verification methods, authoring mappings and Contract Portal audit evidence." },
  { id: "standards-performance", path: "/standards/performance", title: "Performance", group: "Standards", icon: "fa-gauge-high", phase: 32, status: "available", description: "Machine-readable performance rules, budgets, portal measurements, loading boundaries and third-party performance standards." },

  { id: "registry-index", path: "/registry", title: "Registry Index", group: "Registry", icon: "fa-database", phase: 2, status: "available", description: "Browse, search, filter and inspect every authoritative definition currently indexed by NEXT F Contracts." },
  { id: "registry-relationships", path: "/registry/relationships", title: "Relationship Explorer", group: "Registry", icon: "fa-circle-nodes", phase: 24, status: "available", description: "Trace incoming/outgoing relationships, dependencies, impact, permissions, Events and shortest Registry paths." },
  { id: "registry-core", path: "/registry/core", title: "Core", group: "Registry", icon: "fa-cubes", phase: 4, status: "available", description: "Shared identity, tenant scope, publishing, revision and audit contracts." },
  { id: "registry-fields", path: "/registry/fields", title: "Fields", group: "Registry", icon: "fa-list-check", phase: 3, status: "available", description: "Primitive reusable field definitions, value semantics, editor metadata and validation rules." },
  { id: "registry-shared", path: "/registry/shared", title: "Shared", group: "Registry", icon: "fa-layer-group", phase: 4, status: "available", description: "Reusable address, media, link, CTA, contact and external reference schemas." },
  { id: "registry-content", path: "/registry/content", title: "Content", group: "Registry", icon: "fa-file-lines", phase: 5, status: "available", description: "Pages, blogs, documentation, services, reusable content and custom collections." },
  { id: "registry-blocks", path: "/registry/blocks", title: "Blocks", group: "Registry", icon: "fa-table-columns", phase: 6, status: "available", description: "Reusable structured page-section Blocks and nested Block helper schemas." },
  { id: "registry-seo", path: "/registry/seo", title: "SEO", group: "Registry", icon: "fa-magnifying-glass-chart", phase: 7, status: "available", description: "SEO metadata, keywords, canonical, robots, structured data, redirects, sitemaps, audits, link health and search performance." },
  { id: "registry-forms", path: "/registry/forms", title: "Forms", group: "Registry", icon: "fa-rectangle-list", phase: 8, status: "available", description: "Forms, fields, submissions, leads, spam and conversion mappings." },
  { id: "registry-commerce", path: "/registry/commerce", title: "Commerce", group: "Registry", icon: "fa-cart-shopping", phase: 11, status: "available", description: "Catalog, inventory, cart, checkout, orders, payments, shipping and returns." },
  { id: "registry-commerce-rules", path: "/registry/commerce-rules", title: "Commerce Rules", group: "Registry", icon: "fa-scale-balanced", phase: 12, status: "available", description: "Cross-entity commerce invariants, state machines, command policies, idempotency and reconciliation rules." },
  { id: "registry-marketing", path: "/registry/marketing", title: "Marketing", group: "Registry", icon: "fa-bullseye", phase: 9, status: "available", description: "Provider-neutral tracking, analytics, conversions, campaign attribution, consent, event destinations and reporting." },

  { id: "platform-modules", path: "/platform/modules", title: "Modules", group: "Platform", icon: "fa-table-cells-large", phase: 17, status: "available", description: "Module dependencies, capabilities and CMS/Admin navigation metadata." },
  { id: "platform-permissions", path: "/platform/permissions", title: "Permissions", group: "Platform", icon: "fa-key", phase: 15, status: "available", description: "Canonical domain.resource.action permission identifiers, roles, scope binding and deny-by-default authorization rules." },
  { id: "platform-integrations", path: "/platform/integrations", title: "Integrations", group: "Platform", icon: "fa-plug", phase: 10, status: "available", description: "Provider-neutral connector contracts and third-party integration metadata." },
  { id: "platform-api", path: "/platform/api", title: "API", group: "Platform", icon: "fa-code-branch", phase: 18, status: "available", description: "Public Content, Public Interaction, Customer CMS, NEXT F Admin, Commerce, Event and Webhook API contracts." },
  { id: "platform-customer-cms-ui", path: "/platform/customer-cms-ui", title: "Customer CMS UI", group: "Platform", icon: "fa-pen-ruler", phase: 19, status: "available", description: "Declarative Customer CMS resource profiles, editors, layouts, actions and field bindings." },
  { id: "platform-admin-ui", path: "/platform/admin-ui", title: "NEXT F Admin UI", group: "Platform", icon: "fa-user-shield", phase: 20, status: "available", description: "Internal-only Admin profiles, Site/Organization 360, diagnostics, migrations, support context and privileged controls." },

  { id: "events-registry", path: "/events/registry", title: "Event Registry", group: "Events", icon: "fa-bolt", phase: 13, status: "available", description: "Canonical fact-based event names, producers, consumers and payload contracts." },
  { id: "events-webhooks", path: "/events/webhooks", title: "Webhooks", group: "Events", icon: "fa-arrow-right-arrow-left", phase: 14, status: "available", description: "Webhook subscriptions, deliveries, signatures, retries and idempotency." },

  { id: "development-site-manifest", path: "/development/site-manifest", title: "Site Manifest", group: "Development", icon: "fa-file-code", phase: 16, status: "available", description: "Authoritative nextf.site.json specification for Site identity, contract pinning, environments, modules, runtime and supported integrations." },
  { id: "development-codex", path: "/development/codex", title: "Codex", group: "Development", icon: "fa-terminal", phase: 21, status: "available", description: "Permanent AI development standard and contract-first agent workflow." },
  { id: "development-validation", path: "/development/validation", title: "Validation", group: "Development", icon: "fa-circle-check", phase: 33, status: "available", description: "Browser and CLI validation of manifests, modules and contract usage." },
  { id: "development-examples", path: "/development/examples", title: "Examples", group: "Development", icon: "fa-flask", phase: 22, status: "available", description: "Complete reference Site compositions for corporate, service, lead generation, commerce, documentation and custom builds." },
  { id: "development-starters", path: "/development/starters", title: "Starter Packs", group: "Development", icon: "fa-box-open", phase: 35, status: "available", description: "Framework-neutral customer Site bootstrap packs with pinned manifests, contract maps, Codex handoff and validation guidance." },

  { id: "lifecycle-versions", path: "/lifecycle/versions", title: "Versions", group: "Lifecycle", icon: "fa-tags", phase: 0, status: "available", description: "Semantic versioning, status lifecycle and site version pinning rules." },
  { id: "lifecycle-compatibility", path: "/lifecycle/compatibility", title: "Compatibility Center", group: "Lifecycle", icon: "fa-shield-check", phase: 26, status: "available", description: "Assess release readiness, platform surfaces and reference Site compatibility from exact contract evidence." },
  { id: "lifecycle-diff", path: "/lifecycle/diff", title: "Contract Diff", group: "Lifecycle", icon: "fa-code-compare", phase: 25, status: "available", description: "Compare exact Registry releases, classify structural changes and review compatibility impact before upgrades." },
  { id: "lifecycle-migrations", path: "/lifecycle/migrations", title: "Migrations", group: "Lifecycle", icon: "fa-route", phase: 28, status: "planned", description: "Migration guidance for compatible and breaking contract transitions." },
  { id: "lifecycle-deprecations", path: "/lifecycle/deprecations", title: "Deprecations", group: "Lifecycle", icon: "fa-triangle-exclamation", phase: 28, status: "available", description: "Operational deprecation records, replacement guidance, support windows, migration impact and historical removal discovery." },
  { id: "lifecycle-changelog", path: "/lifecycle/changelog", title: "Changelog", group: "Lifecycle", icon: "fa-clock-rotate-left", phase: 27, status: "available", description: "Authoritative release notes with categorized changes, provenance, exact-history evidence and Diff/Compatibility links." }
];

export const routeByPath = new Map(routes.map((route) => [route.path, route]));
export const routeById = new Map(routes.map((route) => [route.id, route]));
