import { icon, escapeHtml, prettyJson } from "./utils.js";
const e=escapeHtml;
const categoryLabels={
  foundation:"Foundation",endpoints:"Endpoints",subscriptions:"Subscriptions",payload:"Payload & HTTP",
  security:"Signing & Security",delivery:"Delivery",resilience:"Retry & Resilience",operations:"Operations & Observability"
};
function header(title,desc,actions=""){return `<header class="page-header"><div class="page-header__copy"><p class="page-header__eyebrow">Events</p><h1>${e(title)}</h1><p>${e(desc)}</p></div>${actions?`<div class="page-header__actions">${actions}</div>`:""}</header>`;}
function src(id){const s=id.split(".",2)[1].replace(/([a-z0-9])([A-Z])/g,"$1-$2").toLowerCase();return `./registry/webhooks/definitions/${s}.json`;}
function refCell(f){const id=f.primitive||f.schema||f.itemsPrimitive||f.itemsSchema;if(!id)return "—";return `<a href="#/registry/item/${encodeURIComponent(id)}"><code>${e(id)}</code></a>${f.itemsPrimitive||f.itemsSchema?' <span class="tag">many</span>':''}`;}
function schemaCards(engine,filters){
 const rows=engine.search(filters.q??"",{...filters,view:"schemas"});
 if(!rows.length)return `<div class="registry-empty paper-card"><span class="registry-empty__icon">${icon("fa-webhook")}</span><h3>No webhook contracts match</h3><p>Change the search or filters.</p></div>`;
 return `<div class="webhook-card-grid">${rows.map(s=>`<article class="paper-card webhook-card"><div class="webhook-card__top"><div><span class="webhook-category">${e(categoryLabels[s.category]??s.category)}</span><h3><a href="#/registry/item/${encodeURIComponent(s.$id)}">${e(s.name)}</a></h3><code>${e(s.$id)}</code></div><span class="status-badge status-badge--stable">Stable</span></div><p>${e(s.description)}</p><div class="webhook-card__meta"><span>${icon("fa-shapes")} ${e(s.webhookModel.kind)}</span><span>${icon("fa-list")} ${s.fields.length} fields</span><span>${icon("fa-shield-halved")} ${s.validationRules.length} rules</span><span>${icon(s.cms?.customerVisible?"fa-user":"fa-lock")} ${s.cms?.customerVisible?"Customer configurable":"Internal/Admin"}</span></div><a class="webhook-card__open" href="#/registry/item/${encodeURIComponent(s.$id)}">Inspect contract ${icon("fa-arrow-right")}</a></article>`).join("")}</div>`;
}
function eventCards(engine,filters){
 const rows=engine.search(filters.q??"",{...filters,view:"events"});
 if(!rows.length)return `<div class="registry-empty paper-card"><span class="registry-empty__icon">${icon("fa-bolt")}</span><h3>No eligible Events match</h3><p>Change the search or sensitivity filter.</p></div>`;
 return `<div class="webhook-event-list">${rows.map(ev=>`<a class="paper-card webhook-event-row" href="#/registry/item/${encodeURIComponent(ev.eventKey)}"><div><div class="webhook-event-row__title"><code>${e(ev.eventKey)}</code><span class="status-badge status-badge--stable">Eligible</span></div><strong>${e(ev.name)}</strong><p>${e(ev.description)}</p></div><div class="webhook-event-row__meta"><span>${e(ev.category)}</span><span>${e(ev.producerKey)}</span><span>${e(ev.dataPolicy?.sensitivity??"internal")}</span>${icon("fa-chevron-right")}</div></a>`).join("")}</div>`;
}
export function renderWebhooksResults(engine,filters={}){return filters.view==="events"?eventCards(engine,filters):schemaCards(engine,filters);}
export function renderWebhooksIndex(engine,filters={}){
 const count=engine.search(filters.q??"",filters).length;
 const cats=engine.data.categories.map(x=>`<option value="${e(x.key)}" ${filters.category===x.key?"selected":""}>${e(x.label)}</option>`).join("");
 const sens=engine.sensitivities.map(x=>`<option value="${e(x)}" ${filters.sensitivity===x?"selected":""}>${e(x)}</option>`).join("");
 const d=engine.data.defaultPolicies;
 return `${header("Webhooks","Canonical endpoint verification, subscriptions, HMAC signing, Event exposure, outbound delivery, retries, dead-lettering and diagnostics for every NEXT F Site.",`<div class="header-actions"><span class="status-badge status-badge--stable">Phase 14</span><span class="tag">${engine.schemas.length} contracts</span><span class="tag">${engine.events.length} eligible Events</span></div>`)}
 <div class="stack stack--lg">
 <div class="registry-source-bar" role="status"><span>${icon("fa-database")} Runtime source</span><strong>${engine.source==="authoritative-json"?"Authoritative Webhook JSON":"Generated local fallback"}</strong><span class="tag">v${e(engine.data.registryVersion)}</span></div>
 <section class="webhook-hero">
  <article class="paper-card"><div class="paper-card__body"><h2>Event truth, webhook transport</h2><p>A canonical Event is created by an authoritative domain first. Webhook delivery only transports eligible Events to verified external destinations; it never becomes the business source of truth.</p><div class="webhook-flow"><span>Domain commit</span><i class="fa-solid fa-arrow-right"></i><span>Canonical Event</span><i class="fa-solid fa-arrow-right"></i><span>Subscription</span><i class="fa-solid fa-arrow-right"></i><span>Logical Delivery</span><i class="fa-solid fa-arrow-right"></i><span>HTTP Attempts</span><i class="fa-solid fa-arrow-right"></i><span>Receiver</span></div></div></article>
  <article class="paper-card"><div class="paper-card__body"><div class="webhook-summary-grid"><div><span>Contracts</span><strong>${engine.schemas.length}</strong></div><div><span>Eligible Events</span><strong>${engine.events.length}</strong></div><div><span>Categories</span><strong>${engine.data.categories.length}</strong></div><div><span>Signing</span><strong>${e(d.signature.algorithm)}</strong></div></div></div></article>
 </section>
 <section class="webhook-security-strip"><div>${icon("fa-shield-halved")}<span><strong>Signed by default.</strong> Every delivery uses HMAC-SHA256 over the exact raw UTF-8 body with timestamp-based replay resistance.</span></div><div>${icon("fa-network-wired")}<span><strong>SSRF-resistant endpoints.</strong> HTTPS public-internet destinations only in V1; redirects and private/reserved addresses are blocked.</span></div></section>
 <section class="paper-card"><div class="paper-card__header"><div><h2>Explore Webhook contracts</h2><p>Inspect schemas or switch to the exact allow-list of Event Registry definitions currently eligible for webhook delivery.</p></div><button class="button button--ghost button--compact" type="button" data-webhooks-clear>${icon("fa-rotate-left")} Clear</button></div><div class="paper-card__body"><div class="registry-toolbar">
 <label class="search-field"><span class="sr-only">Search Webhooks</span>${icon("fa-magnifying-glass")}<input type="search" value="${e(filters.q??"")}" placeholder="Search endpoint, signature, delivery, order.paid..." data-webhooks-q></label>
 <label><span class="sr-only">View</span><select data-webhooks-view><option value="schemas" ${filters.view!=="events"?"selected":""}>Webhook contracts</option><option value="events" ${filters.view==="events"?"selected":""}>Eligible Events</option></select></label>
 <label data-webhooks-category-wrap><span class="sr-only">Category</span><select data-webhooks-category><option value="">All categories</option>${cats}</select></label>
 <label data-webhooks-sensitivity-wrap><span class="sr-only">Sensitivity</span><select data-webhooks-sensitivity><option value="">All sensitivities</option>${sens}</select></label>
 <label data-webhooks-config-wrap><span class="sr-only">Visibility</span><select data-webhooks-configurable><option value="">All access</option><option value="customer" ${filters.configurable==="customer"?"selected":""}>Customer configurable</option><option value="admin" ${filters.configurable==="admin"?"selected":""}>Admin visible</option></select></label>
 <div class="field-filter-summary"><span>Results</span><strong data-webhooks-count>${count}</strong></div>
 </div></div></section>
 <section data-webhooks-results>${renderWebhooksResults(engine,filters)}</section>
 <section class="webhook-policy-grid">
  <article class="paper-card"><div class="paper-card__header"><div><h2>Request protocol</h2><p>Stable receiver-facing transport defaults.</p></div></div><div class="paper-card__body webhook-kv"><div><span>Method</span><strong>POST</strong></div><div><span>Payload limit</span><strong>256 KiB</strong></div><div><span>Connect timeout</span><strong>${d.timeouts.connectTimeoutSeconds}s</strong></div><div><span>Total timeout</span><strong>${d.timeouts.totalTimeoutSeconds}s</strong></div><div><span>Redirects</span><strong>Never followed</strong></div><div><span>Content</span><strong>UTF-8 JSON</strong></div></div></article>
  <article class="paper-card"><div class="paper-card__header"><div><h2>Retry & health</h2><p>Finite resilient delivery, never infinite retries.</p></div></div><div class="paper-card__body webhook-kv"><div><span>Total attempts</span><strong>${d.retry.maxAttempts}</strong></div><div><span>Jitter</span><strong>${d.retry.jitterPercent}%</strong></div><div><span>Degraded after</span><strong>${d.health.degradedAfterConsecutiveFailures} failures</strong></div><div><span>Auto-pause after</span><strong>${d.health.pauseAfterConsecutiveFailures} failures</strong></div><div><span>Paused queue</span><strong>${d.health.pauseQueueRetentionHours}h</strong></div><div><span>Redelivery window</span><strong>${d.retention.manualRedeliveryWindowDays}d</strong></div></div></article>
  <article class="paper-card"><div class="paper-card__header"><div><h2>Signature V1</h2><p>Receiver verification contract.</p></div></div><div class="paper-card__body webhook-kv"><div><span>Algorithm</span><strong>${e(d.signature.algorithm)}</strong></div><div><span>Tolerance</span><strong>${d.signature.timestampToleranceSeconds}s</strong></div><div><span>Secret entropy</span><strong>≥ ${d.signature.minimumSecretEntropyBytes} bytes</strong></div><div><span>Rotation overlap</span><strong>${d.signature.rotationOverlapHours}h</strong></div><div class="webhook-kv__wide"><span>Signed input</span><code>&lt;timestamp&gt;.&lt;exact raw body bytes&gt;</code></div></div></article>
 </section>
 <section class="paper-card"><div class="paper-card__header"><div><h2>Receiver essentials</h2><p>The minimum implementation contract for every external receiver.</p></div><a class="button button--secondary button--compact" href="./standards/22-webhook-registry-standard.md">${icon("fa-file-lines")} Full standard</a></div><div class="paper-card__body webhook-receiver-grid"><div><strong>1. Read raw body</strong><p>Do not parse and reserialize before signature verification.</p></div><div><strong>2. Validate timestamp + HMAC</strong><p>Use constant-time comparison and reject stale requests.</p></div><div><strong>3. Deduplicate</strong><p>Use the canonical Event ID / logical Delivery identity for idempotency.</p></div><div><strong>4. Return quickly</strong><p>Return a 2xx after safe acceptance; perform expensive work asynchronously where appropriate.</p></div></div></section>
 </div>`;
}
function fieldRows(fields){return `<div class="registry-table-wrap"><table class="registry-table"><thead><tr><th>Field</th><th>Contract</th><th>Required</th><th>Description</th></tr></thead><tbody>${fields.map(f=>`<tr><td><code>${e(f.key)}</code></td><td>${refCell(f)}</td><td>${f.required?"Yes":"No"}${f.nullable?" · nullable":""}</td><td>${e(f.description)}</td></tr>`).join("")}</tbody></table></div>`;}
export function renderWebhooksDetail(registry,item,s){
 if(!s)return `<div class="registry-empty paper-card"><h2>Webhook contract unavailable</h2></div>`;
 const relationships=(s.relationships||[]).length?`<div class="relationship-list">${s.relationships.map(r=>`<div><span class="tag">${e(r.type)}</span><a href="#/registry/item/${encodeURIComponent(r.target)}"><code>${e(r.target)}</code></a><p>${e(r.description||"")}</p></div>`).join("")}</div>`:`<p class="text-muted">No direct cross-contract relationships.</p>`;
 return `${header(s.name,s.description,`<div class="header-actions"><span class="status-badge status-badge--stable">Stable</span><span class="tag">v${e(s.version)}</span></div>`)}
 <div class="stack stack--lg">
 <section class="schema-identity paper-card"><div class="paper-card__body"><div><span class="webhook-category">${e(categoryLabels[s.category]??s.category)}</span><h2><code>${e(s.$id)}</code></h2><p>${e(s.purpose)}</p></div><div class="schema-actions"><button class="button button--primary button--compact" data-copy-value="${e(s.$id)}" data-copy-label="Webhook contract ID copied">${icon("fa-copy")} Copy ID</button><button class="button button--secondary button--compact" data-copy-webhook-json="${e(s.$id)}">${icon("fa-code")} Copy JSON</button><a class="button button--secondary button--compact" href="${src(s.$id)}">${icon("fa-file-code")} Source</a></div></div></section>
 <section class="webhook-detail-summary"><div class="paper-card"><span>Category</span><strong>${e(categoryLabels[s.category]??s.category)}</strong></div><div class="paper-card"><span>Model</span><strong>${e(s.webhookModel.kind)}</strong></div><div class="paper-card"><span>Fields</span><strong>${s.fields.length}</strong></div><div class="paper-card"><span>Validation rules</span><strong>${s.validationRules.length}</strong></div></section>
 <section class="paper-card"><div class="paper-card__header"><div><h2>Fields</h2><p>Canonical structure and reusable field/schema dependencies.</p></div></div><div class="paper-card__body paper-card__body--flush">${fieldRows(s.fields)}</div></section>
 <div class="detail-two-col">
 <section class="paper-card"><div class="paper-card__header"><div><h2>Validation</h2></div></div><div class="paper-card__body field-rule-grid">${(s.validationRules||[]).map(r=>`<div><code>${e(r.id)}</code><p>${e(r.description)}</p></div>`).join("")}</div></section>
 <section class="paper-card"><div class="paper-card__header"><div><h2>Relationships</h2></div></div><div class="paper-card__body">${relationships}</div></section>
 </div>
 <section class="paper-card"><div class="paper-card__header"><div><h2>CMS & delivery boundary</h2></div></div><div class="paper-card__body webhook-boundary-grid"><div><span>Customer visible</span><strong>${s.cms?.customerVisible?"Yes":"No"}</strong></div><div><span>NEXT F Admin</span><strong>${s.cms?.adminVisible?"Yes":"No"}</strong></div><div><span>Public website</span><strong>No</strong></div><div><span>Sensitivity</span><strong>${e(s.webhookModel.dataSensitivity)}</strong></div></div></section>
 <section class="paper-card"><div class="paper-card__header"><div><h2>Authoritative JSON</h2><p>Machine-readable definition used by NEXT F implementations and Codex.</p></div><button class="button button--secondary button--compact" data-copy-webhook-json="${e(s.$id)}">${icon("fa-copy")} Copy JSON</button></div><div class="paper-card__body"><pre class="code-panel"><code>${e(prettyJson(s))}</code></pre></div></section>
 </div>`;
}
