import fs from "node:fs";import path from "node:path";import crypto from "node:crypto";import {spawnSync} from "node:child_process";
const root=path.resolve(process.cwd()),version=fs.readFileSync(path.join(root,"VERSION"),"utf8").trim();const failures=[],passes=[];const check=(n,c,d="")=>c?passes.push(n):failures.push(`${n}${d?`: ${d}`:""}`);const read=r=>fs.readFileSync(path.join(root,r),"utf8");const json=r=>{try{return JSON.parse(read(r))}catch(e){failures.push(`Valid JSON ${r}: ${e.message}`);return null}};
check("Version is 0.7.0",version==="0.7.0",version);
for(const rel of ["standards/14-block-contract-standard.md","registry/blocks/categories.json","registry/blocks/block-definition.schema.json","registry/blocks/index.json","js/block-registry-engine.js","js/generated-blocks.js","css/blocks.css","scripts/sync-block-registry.mjs","checks/phase-6-acceptance.json"])check(`File exists ${rel}`,fs.existsSync(path.join(root,rel)));
const idx=json("registry/blocks/index.json"),fields=json("registry/fields/index.json"),core=json("registry/core/index.json"),content=json("registry/content/index.json"),registry=json("registry/registry.json"),domains=json("registry/domains.json"),types=json("registry/types.json"),acceptance=json("checks/phase-6-acceptance.json");
if(idx&&fields&&core&&content&&registry){
 check("Block registry version",idx.registryVersion===version,idx.registryVersion);check("Exactly 29 Block definitions",idx.schemas.length===29,idx.schemas.length);check("Exactly 20 section Blocks",idx.sectionBlockCount===20,idx.sectionBlockCount);check("Exactly 9 embedded helpers",idx.embeddedSchemaCount===9,idx.embeddedSchemaCount);
 const ids=idx.schemas.map(x=>x.$id);check("Block IDs unique",ids.length===new Set(ids).size);check("Block IDs canonical",ids.every(x=>/^blocks\.[a-z][A-Za-z0-9]*$/.test(x)));
 const expected=["blocks.hero","blocks.richText","blocks.textImage","blocks.featureGrid","blocks.services","blocks.stats","blocks.gallery","blocks.video","blocks.testimonials","blocks.faq","blocks.logoGrid","blocks.team","blocks.locations","blocks.pricing","blocks.process","blocks.cta","blocks.form","blocks.documents","blocks.relatedContent","blocks.custom"];
 expected.forEach(id=>check(`Canonical section exists ${id}`,ids.includes(id)));
 const helpers=["blocks.heading","blocks.actionGroup","blocks.featureItem","blocks.statItem","blocks.galleryItem","blocks.logoItem","blocks.pricingPlan","blocks.processStep","blocks.relatedContentItem"];helpers.forEach(id=>check(`Embedded helper exists ${id}`,ids.includes(id)));
 const fmap=new Map(fields.fields.map(x=>[x.$id,x])), cmap=new Map(core.schemas.map(x=>[x.$id,x])), contentMap=new Map(content.schemas.map(x=>[x.$id,x])), bmap=new Map(idx.schemas.map(x=>[x.$id,x])), rmap=new Map(registry.items.map(x=>[x.id,x]));
 for(const b of idx.schemas){
  for(const k of ["$id","name","version","status","domain","category","description","purpose"])check(`${b.$id} has ${k}`,typeof b[k]==="string"&&b[k].length>0);check(`${b.$id} version`,b.version===version,b.version);check(`${b.$id} stable`,b.status==="stable");check(`${b.$id} blocks domain`,b.domain==="blocks");check(`${b.$id} model kind`,["section","embedded"].includes(b.blockModel?.kind));check(`${b.$id} placement matches kind`,b.blockModel?.placement===(b.blockModel?.kind==="section"?"page-section":"nested-only"));check(`${b.$id} presentation developer controlled`,b.blockModel?.developerControlledPresentation===true);check(`${b.$id} no arbitrary HTML`,b.blockModel?.allowsArbitraryHtml===false);check(`${b.$id} no arbitrary CSS`,b.blockModel?.allowsArbitraryCss===false);check(`${b.$id} no arbitrary JS`,b.blockModel?.allowsArbitraryScript===false);check(`${b.$id} fields`,Array.isArray(b.fields)&&b.fields.length>0);check(`${b.$id} relationships`,Array.isArray(b.relationships));check(`${b.$id} rules`,Array.isArray(b.validationRules));check(`${b.$id} CMS`,b.cms&&typeof b.cms.label==="string"&&typeof b.cms.customerVisible==="boolean");check(`${b.$id} presentation`,b.presentation?.layoutControlledBy==="frontend"&&b.presentation?.styleControlledBy==="frontend");check(`${b.$id} accessibility`,Array.isArray(b.accessibility?.requirements));check(`${b.$id} delivery`,typeof b.delivery?.publicAllowed==="boolean");check(`${b.$id} examples`,Array.isArray(b.examples?.valid)&&Array.isArray(b.examples?.invalid));check(`${b.$id} notes`,Array.isArray(b.notes));
  const keys=b.fields.map(f=>f.key);check(`${b.$id} field keys unique`,keys.length===new Set(keys).size);
  for(const f of b.fields){check(`${b.$id}.${f.key} one source`,Boolean(f.primitive)!==Boolean(f.schema));if(f.primitive){const p=fmap.get(f.primitive);check(`${b.$id}.${f.key} primitive resolves ${f.primitive}`,Boolean(p));if(p&&f.config){const allowed=new Set(p.supportedConfig);for(const c of Object.keys(f.config))check(`${b.$id}.${f.key} config supported ${c}`,allowed.has(c),f.primitive);}}if(f.schema)check(`${b.$id}.${f.key} schema resolves ${f.schema}`,bmap.has(f.schema)||cmap.has(f.schema)||contentMap.has(f.schema)||rmap.has(f.schema),f.schema);if(f.itemsSchema)check(`${b.$id}.${f.key} items schema resolves`,bmap.has(f.itemsSchema),f.itemsSchema);}
  for(const rel of b.relationships)check(`${b.$id} relationship resolves ${rel.target}`,bmap.has(rel.target)||cmap.has(rel.target)||contentMap.has(rel.target)||fmap.has(rel.target)||rmap.has(rel.target),rel.target);
  check(`Main registry indexes ${b.$id}`,rmap.has(b.$id));
 }
 check("Blocks standard indexed",rmap.has("blocks.blockContractStandard"));check("Blocks index registered",rmap.has("blocks.blockRegistry"));check("Blocks domain registered",domains.domains.some(x=>x.id==="blocks"));check("Block type registered",types.types.some(x=>x.id==="block"));
 const sectionSet=new Set(idx.schemas.filter(x=>x.blockModel.kind==="section").map(x=>x.$id));for(const id of expected)check(`Page section eligible ${id}`,sectionSet.has(id));for(const id of helpers)check(`Helper not page-section eligible ${id}`,!sectionSet.has(id));
 check("Pricing explicitly non-commerce authority",bmap.get("blocks.pricing")?.validationRules?.some(r=>r.id==="notCommerceAuthority"));check("Custom requires registered extension",bmap.get("blocks.custom")?.validationRules?.some(r=>r.id==="extensionRegistered"));check("Form defers Phase 8",bmap.get("blocks.form")?.futureBindings?.forms==="phase-8-required");check("Video prohibits raw embed",bmap.get("blocks.video")?.validationRules?.some(r=>r.id==="noRawEmbed"));check("Page Section requires Phase 6 blocks",contentMap.get("content.pageSection")?.futureBindings?.blocks==="phase-6-required");
 check("No Phase 7 SEO contracts fabricated",!registry.items.some(i=>i.domain==="seo"&&i.phase===7&&i.managedBy));
}
const raw=read("registry/blocks/index.json"),digest=crypto.createHash("sha256").update(raw).digest("hex"),gen=read("js/generated-blocks.js");check("Generated block fallback source",gen.includes("Source: registry/blocks/index.json"));check("Generated block fallback checksum",gen.includes(digest),digest);check("Generated block fallback export",gen.includes("GENERATED_BLOCKS ="));
const routes=read("js/routes.js"),router=read("js/router.js"),pages=read("js/pages.js"),html=read("index.html"),app=read("js/app.js");check("Blocks route available",routes.includes('path: "/registry/blocks"')&&routes.includes('phase: 6, status: "available"'));check("Block index renderer",pages.includes("renderBlocksIndex"));check("Block detail renderer",pages.includes("renderBlockDetail"));check("Block list binding",router.includes("bindBlockList"));check("Block engine loads authoritative JSON",read("js/block-registry-engine.js").includes('fetch("./registry/blocks/index.json"'));check("Block generated fallback wired",read("js/block-registry-engine.js").includes("GENERATED_BLOCKS"));check("App loads Blocks",app.includes("loadBlocks"));check("Block CSS loaded",html.includes('./css/blocks.css'));check("Portal version visible",html.includes("v0.7.0"));check("Blocks sidebar visible",html.includes('#/registry/blocks'));
if(acceptance){check("Phase 6 acceptance version",acceptance.version===version);check("All Phase 6 acceptance checks passed",acceptance.checks.every(x=>x.passed===true));}
for(const rel of ["js/app.js","js/router.js","js/routes.js","js/pages.js","js/search.js","js/utils.js","js/registry-engine.js","js/generated-registry.js","js/field-registry-engine.js","js/generated-fields.js","js/core-schema-engine.js","js/generated-core-schemas.js","js/content-schema-engine.js","js/generated-content-schemas.js","js/block-registry-engine.js","js/generated-blocks.js","scripts/generate-registry-bootstrap.mjs","scripts/sync-field-registry.mjs","scripts/sync-core-schema-registry.mjs","scripts/sync-content-schema-registry.mjs","scripts/sync-block-registry.mjs"]){const r=spawnSync(process.execPath,["--check",path.join(root,rel)],{encoding:"utf8"});check(`JavaScript syntax valid ${rel}`,r.status===0,r.stderr.trim());}
const css=fs.readdirSync(path.join(root,"css")).filter(x=>x.endsWith(".css")).map(x=>read(`css/${x}`)).join("\n").toLowerCase();check("Light-only preserved",!css.includes("prefers-color-scheme: dark"));check("No backdrop-filter",!css.includes("backdrop-filter"));check("No 3D transforms",!css.includes("perspective(")&&!css.includes("rotatex(")&&!css.includes("rotatey("));
console.log("NEXT F Contracts Phase 6 validation");console.log(`Version: ${version}`);console.log(`Block Contracts: ${idx?.schemas?.length??0}`);console.log(`Section Blocks: ${idx?.sectionBlockCount??0}`);console.log(`Embedded Helpers: ${idx?.embeddedSchemaCount??0}`);console.log(`Registry items: ${registry?.items?.length??0}`);console.log(`Passes: ${passes.length}`);console.log(`Failures: ${failures.length}`);if(failures.length){console.error("\nFailures:");for(const f of failures)console.error(`- ${f}`);process.exit(1)}console.log("\nPASS - Phase 6 Block Registry is internally consistent.");
