import fs from "node:fs";import path from "node:path";import crypto from "node:crypto";import {spawnSync} from "node:child_process";
const root=path.resolve(process.cwd()),fails=[],passes=[];const check=(n,o,d="")=>o?passes.push(n):fails.push(`${n}${d?`: ${d}`:""}`);const read=(r)=>fs.readFileSync(path.join(root,r),"utf8");const json=(r)=>{try{return JSON.parse(read(r));}catch(e){fails.push(`Valid JSON ${r}: ${e.message}`);return null;}};
const version=read("VERSION").trim();check("Repository version is 0.6.0",version==="0.6.0",version);
const required=["standards/13-content-contract-standard.md","registry/content/categories.json","registry/content/content-schema-definition.schema.json","registry/content/index.json","js/content-schema-engine.js","js/generated-content-schemas.js","css/content-schemas.css","scripts/sync-content-schema-registry.mjs","checks/phase-5-acceptance.json"];
required.forEach((r)=>check(`File exists: ${r}`,fs.existsSync(path.join(root,r))));
const idx=json("registry/content/index.json"),cats=json("registry/content/categories.json"),fields=json("registry/fields/index.json"),core=json("registry/core/index.json"),registry=json("registry/registry.json"),domains=json("registry/domains.json"),acceptance=json("checks/phase-5-acceptance.json");
for(const [n,o] of Object.entries({idx,cats,registry,domains}))if(o)check(`${n} registryVersion`,o.registryVersion===version,o.registryVersion);
if(idx&&cats&&fields&&core&&registry){const schemas=idx.schemas,ids=schemas.map(x=>x.$id),contentMap=new Map(schemas.map(x=>[x.$id,x])),fieldMap=new Map(fields.fields.map(x=>[x.$id,x])),coreMap=new Map(core.schemas.map(x=>[x.$id,x])),regMap=new Map(registry.items.map(x=>[x.id,x])),catIds=new Set(cats.categories.map(x=>x.id));
 check("Exactly 20 Content Contracts",schemas.length===20,schemas.length);check("definitionCount is 20",idx.definitionCount===20,idx.definitionCount);check("IDs unique",ids.length===new Set(ids).size);check("IDs canonical",ids.every(id=>/^content\.[a-z][A-Za-z0-9]*$/.test(id)));
 const expected=["content.page","content.pageSection","content.reusableContent","content.blogPost","content.blogCategory","content.blogTag","content.author","content.documentationCollection","content.documentationCategory","content.documentationArticle","content.faq","content.service","content.testimonial","content.teamMember","content.location","content.navigation","content.navigationItem","content.legalPage","content.customCollection","content.customCollectionEntry"];
 expected.forEach(id=>check(`Expected Content Contract exists: ${id}`,ids.includes(id)));
 const files=fs.readdirSync(path.join(root,"registry/content/definitions")).filter(x=>x.endsWith(".json"));check("Exactly 20 authoritative content definition files",files.length===20,files.length);
 const defIds=files.map(f=>json(`registry/content/definitions/${f}`)?.$id).filter(Boolean);check("Index matches definition files",ids.slice().sort().join("|")===defIds.slice().sort().join("|"));
 for(const s of schemas){for(const k of ["$id","name","version","status","domain","category","description","purpose"])check(`${s.$id} has ${k}`,typeof s[k]==="string"&&s[k].length>0);check(`${s.$id} stable`,s.status==="stable");check(`${s.$id} version 0.6.0`,s.version===version,s.version);check(`${s.$id} content domain`,s.domain==="content");check(`${s.$id} controlled category`,catIds.has(s.category),s.category);check(`${s.$id} contentModel`,s.contentModel&&["entity","embedded","configuration"].includes(s.contentModel.kind)&&["required","optional","none"].includes(s.contentModel.routing)&&typeof s.contentModel.customerManaged==="boolean"&&typeof s.contentModel.supportsPublishing==="boolean"&&typeof s.contentModel.supportsRevision==="boolean");check(`${s.$id} fields`,Array.isArray(s.fields)&&s.fields.length>0);check(`${s.$id} relationships`,Array.isArray(s.relationships));check(`${s.$id} validationRules`,Array.isArray(s.validationRules));check(`${s.$id} CMS metadata`,s.cms&&typeof s.cms.label==="string"&&typeof s.cms.customerVisible==="boolean"&&typeof s.cms.adminVisible==="boolean"&&typeof s.cms.editorMode==="string"&&Array.isArray(s.cms.primaryActions));check(`${s.$id} delivery`,s.delivery&&typeof s.delivery.publicAllowed==="boolean"&&typeof s.delivery.notes==="string");check(`${s.$id} futureBindings`,s.futureBindings&&Object.prototype.hasOwnProperty.call(s.futureBindings,"seo")&&Object.prototype.hasOwnProperty.call(s.futureBindings,"events")&&Object.prototype.hasOwnProperty.call(s.futureBindings,"permissions"));check(`${s.$id} examples`,s.examples&&Array.isArray(s.examples.valid)&&Array.isArray(s.examples.invalid));check(`${s.$id} notes`,Array.isArray(s.notes));
  const keys=s.fields.map(f=>f.key);check(`${s.$id} field keys unique`,keys.length===new Set(keys).size);
  for(const f of s.fields){check(`${s.$id}.${f.key} one source`,Boolean(f.primitive)!==Boolean(f.schema));check(`${s.$id}.${f.key} required bool`,typeof f.required==="boolean");check(`${s.$id}.${f.key} nullable bool`,typeof f.nullable==="boolean");check(`${s.$id}.${f.key} description`,typeof f.description==="string"&&f.description.length>0);if(f.primitive){const p=fieldMap.get(f.primitive);check(`${s.$id}.${f.key} primitive resolves ${f.primitive}`,Boolean(p));if(p&&f.config){const allowed=new Set(p.supportedConfig);for(const cfg of Object.keys(f.config))check(`${s.$id}.${f.key} config supported ${cfg}`,allowed.has(cfg),f.primitive);if(f.primitive==="fields.relation"&&f.config.relationshipTarget)check(`${s.$id}.${f.key} relation target resolves ${f.config.relationshipTarget}`,contentMap.has(f.config.relationshipTarget)||coreMap.has(f.config.relationshipTarget)||regMap.has(f.config.relationshipTarget),f.config.relationshipTarget);}}if(f.schema)check(`${s.$id}.${f.key} nested schema resolves ${f.schema}`,contentMap.has(f.schema)||coreMap.has(f.schema)||regMap.has(f.schema),f.schema);}
  const ruleIds=s.validationRules.map(r=>r.id);check(`${s.$id} validation IDs unique`,ruleIds.length===new Set(ruleIds).size);s.validationRules.forEach(r=>check(`${s.$id} validation described ${r.id}`,typeof r.description==="string"&&r.description.length>0));s.relationships.forEach(r=>check(`${s.$id} relationship target resolves ${r.target}`,contentMap.has(r.target)||coreMap.has(r.target)||fieldMap.has(r.target)||regMap.has(r.target),r.target));
 }
 const page=contentMap.get("content.page");check("Page composes Page Sections",page?.fields?.some(f=>f.key==="sections"&&f.config?.relationshipTarget==="content.pageSection"));check("Page keeps template NEXT F controlled",page?.fields?.find(f=>f.key==="templateKey")?.config?.customerEditable===false);
 const section=contentMap.get("content.pageSection");check("Page Section waits for Phase 6 blocks",section?.futureBindings?.blocks==="phase-6-required");check("Page Section blocks arbitrary executable payloads",section?.validationRules?.some(r=>r.id==="blockPayloadStructured"));
 const post=contentMap.get("content.blogPost");check("Blog Post has title",post?.fields?.some(f=>f.key==="title"));check("Blog Post has slug",post?.fields?.some(f=>f.key==="slug"));check("Blog Post has rich content",post?.fields?.some(f=>f.key==="content"&&f.primitive==="fields.richText"));check("Blog Post has featured media",post?.fields?.some(f=>f.key==="featuredMedia"&&f.schema==="shared.mediaReference"));check("Blog Post has author",post?.fields?.some(f=>f.key==="author"));check("Blog Post has categories",post?.fields?.some(f=>f.key==="categories"));check("Blog Post has tags",post?.fields?.some(f=>f.key==="tags"));check("Blog Post uses editorial workspace",post?.cms?.editorMode==="editorial-workspace");check("Blog SEO deferred to Phase 7",post?.futureBindings?.seo==="phase-7");
 const docs=contentMap.get("content.documentationArticle");check("Documentation Article has collection",docs?.fields?.some(f=>f.key==="collection"));check("Documentation Article has structured content",docs?.fields?.some(f=>f.key==="content"&&f.primitive==="fields.richText"));
 const nav=contentMap.get("content.navigation");check("Navigation contains items",nav?.fields?.some(f=>f.key==="items"&&f.config?.relationshipTarget==="content.navigationItem"));
 const cc=contentMap.get("content.customCollection");check("Custom Collection is NEXT F managed",cc?.contentModel?.customerManaged===false&&cc?.cms?.customerVisible===false);check("Custom Collection has fieldDefinitions",cc?.fields?.some(f=>f.key==="fieldDefinitions"));check("Custom Collection registered fields only",cc?.validationRules?.some(r=>r.id==="registeredFieldsOnly"));
 const ce=contentMap.get("content.customCollectionEntry");check("Custom Entry belongs to Custom Collection",ce?.fields?.some(f=>f.key==="collection"&&f.config?.relationshipTarget==="content.customCollection"));check("Custom Entry data validated by collection",ce?.validationRules?.some(r=>r.id==="dataMatchesCollection"));
 check("No Phase 6 block schemas fabricated",!schemas.some(s=>s.$id.startsWith("blocks.")));check("No Phase 7 SEO fields fabricated",!schemas.some(s=>s.fields.some(f=>f.schema?.startsWith("seo.")||f.primitive?.startsWith("seo."))));
 check("Main registry indexes content standard",regMap.has("content.contentContractStandard"));schemas.forEach(s=>check(`Main registry indexes ${s.$id}`,regMap.has(s.$id)));check("Content domain registered",domains.domains.some(d=>d.id==="content"));
}
const raw=read("registry/content/index.json"),digest=crypto.createHash("sha256").update(raw).digest("hex"),gen=read("js/generated-content-schemas.js");check("Generated content fallback source",gen.includes("Source: registry/content/index.json"));check("Generated content fallback checksum",gen.includes(digest),digest);check("Generated content fallback export",gen.includes("GENERATED_CONTENT_SCHEMAS ="));
const routes=read("js/routes.js"),router=read("js/router.js"),pages=read("js/pages.js"),html=read("index.html");check("Content route available",routes.includes('path: "/registry/content"')&&routes.includes('phase: 5, status: "available"'));check("Content index renderer",pages.includes("renderContentSchemasIndex"));check("Content detail renderer",pages.includes("renderContentSchemaDetail"));check("Content list binding",router.includes("bindContentList"));check("Content engine loads authoritative JSON",read("js/content-schema-engine.js").includes('fetch("./registry/content/index.json"'));check("Content generated fallback",read("js/content-schema-engine.js").includes("GENERATED_CONTENT_SCHEMAS"));check("Content CSS loaded",html.includes('./css/content-schemas.css'));check("Portal version visible",html.includes("v0.6.0"));
if(acceptance){check("Phase 5 acceptance version",acceptance.version===version);check("All acceptance checks passed",acceptance.checks.every(x=>x.passed===true));}
for(const rel of ["js/app.js","js/router.js","js/routes.js","js/pages.js","js/search.js","js/utils.js","js/registry-engine.js","js/generated-registry.js","js/field-registry-engine.js","js/generated-fields.js","js/core-schema-engine.js","js/generated-core-schemas.js","js/content-schema-engine.js","js/generated-content-schemas.js","scripts/generate-registry-bootstrap.mjs","scripts/sync-field-registry.mjs","scripts/sync-core-schema-registry.mjs","scripts/sync-content-schema-registry.mjs"]){const r=spawnSync(process.execPath,["--check",path.join(root,rel)],{encoding:"utf8"});check(`JavaScript syntax valid: ${rel}`,r.status===0,r.stderr.trim());}
const css=fs.readdirSync(path.join(root,"css")).filter(x=>x.endsWith(".css")).map(x=>read(`css/${x}`)).join("\n").toLowerCase();check("Light-only preserved",!css.includes("prefers-color-scheme: dark"));check("No backdrop-filter",!css.includes("backdrop-filter"));check("No 3D transforms",!css.includes("perspective(")&&!css.includes("rotatex(")&&!css.includes("rotatey("));
console.log("NEXT F Contracts Phase 5 validation");console.log(`Version: ${version}`);console.log(`Content Contracts: ${idx?.schemas?.length??0}`);console.log(`Registry items: ${registry?.items?.length??0}`);console.log(`Passes: ${passes.length}`);console.log(`Failures: ${fails.length}`);if(fails.length){console.error("Failures:");fails.forEach(x=>console.error(`- ${x}`));process.exit(1);}console.log("PASS - Phase 5 Content Contracts are internally consistent.");
