import fs from "node:fs";
import path from "node:path";
import crypto from "node:crypto";
import { spawnSync } from "node:child_process";
const root=path.resolve(process.cwd()), failures=[], passes=[];
const check=(name,ok,detail="")=>ok?passes.push(name):failures.push(`${name}${detail?`: ${detail}`:""}`);
const read=(rel)=>fs.readFileSync(path.join(root,rel),"utf8");
const json=(rel)=>{try{return JSON.parse(read(rel));}catch(e){failures.push(`Valid JSON ${rel}: ${e.message}`);return null;}};
const version=read("VERSION").trim();check("Repository version is 0.5.0",version==="0.5.0",version);
const required=["standards/12-shared-core-schema-standard.md","registry/core/categories.json","registry/core/core-schema-definition.schema.json","registry/core/index.json","js/core-schema-engine.js","js/generated-core-schemas.js","css/core-schemas.css","scripts/sync-core-schema-registry.mjs","checks/phase-4-acceptance.json"];
required.forEach((rel)=>check(`File exists: ${rel}`,fs.existsSync(path.join(root,rel))));
const index=json("registry/core/index.json"), categories=json("registry/core/categories.json"), fields=json("registry/fields/index.json"), registry=json("registry/registry.json"), domains=json("registry/domains.json"), types=json("registry/types.json"), acceptance=json("checks/phase-4-acceptance.json");
for(const [name,obj] of Object.entries({index,categories,registry,domains,types})) if(obj)check(`${name} version matches repository`,obj.registryVersion===version,obj.registryVersion);
if(index&&fields&&categories){
 const schemas=index.schemas, ids=schemas.map(x=>x.$id), fieldMap=new Map(fields.fields.map(x=>[x.$id,x])), schemaMap=new Map(schemas.map(x=>[x.$id,x])), catIds=new Set(categories.categories.map(x=>x.id));
 check("Exactly 19 Shared Core Schemas",schemas.length===19,schemas.length);check("definitionCount is 19",index.definitionCount===19,index.definitionCount);check("Schema IDs unique",ids.length===new Set(ids).size);check("Schema IDs canonical",ids.every(id=>/^(core|shared)\.[a-z][A-Za-z0-9]*$/.test(id)));
 const expected=["core.organization","core.site","core.entityIdentity","core.tenantScope","core.actorReference","core.entityReference","core.visibility","core.scheduleWindow","core.publishing","core.versionRecord","core.revisionPointer","core.auditRecord","shared.address","shared.mediaAsset","shared.mediaReference","shared.link","shared.cta","shared.contactPoint","shared.externalReference"];
 expected.forEach(id=>check(`Expected Shared Core schema exists: ${id}`,ids.includes(id)));
 const defDir=path.join(root,"registry/core/definitions"), files=fs.readdirSync(defDir).filter(x=>x.endsWith(".json"));check("Exactly 19 authoritative core definition files",files.length===19,files.length);
 const defIds=files.map(file=>json(`registry/core/definitions/${file}`)?.$id).filter(Boolean);check("Index matches definition files",ids.slice().sort().join("|")===defIds.slice().sort().join("|"));
 for(const schema of schemas){
   for(const key of ["$id","name","version","status","domain","category","description","purpose"])check(`${schema.$id} has ${key}`,typeof schema[key]==="string"&&schema[key].length>0);
   check(`${schema.$id} stable`,schema.status==="stable");check(`${schema.$id} version 0.5.0`,schema.version===version);check(`${schema.$id} controlled category`,catIds.has(schema.category),schema.category);check(`${schema.$id} fields array`,Array.isArray(schema.fields)&&schema.fields.length>0);check(`${schema.$id} relationships array`,Array.isArray(schema.relationships));check(`${schema.$id} validation array`,Array.isArray(schema.validationRules));check(`${schema.$id} CMS metadata`,schema.cms&&typeof schema.cms.customerVisible==="boolean"&&typeof schema.cms.adminVisible==="boolean"&&typeof schema.cms.defaultPlacement==="string");check(`${schema.$id} delivery metadata`,schema.delivery&&typeof schema.delivery.publicAllowed==="boolean"&&typeof schema.delivery.notes==="string");check(`${schema.$id} examples`,schema.examples&&Array.isArray(schema.examples.valid)&&Array.isArray(schema.examples.invalid));check(`${schema.$id} notes`,Array.isArray(schema.notes));
   const keys=schema.fields.map(f=>f.key);check(`${schema.$id} field keys unique`,keys.length===new Set(keys).size);
   for(const f of schema.fields){
     check(`${schema.$id}.${f.key} one value source`,Boolean(f.primitive)!==Boolean(f.schema));check(`${schema.$id}.${f.key} required boolean`,typeof f.required==="boolean");check(`${schema.$id}.${f.key} nullable boolean`,typeof f.nullable==="boolean");check(`${schema.$id}.${f.key} description`,typeof f.description==="string"&&f.description.length>0);
     if(f.primitive){const p=fieldMap.get(f.primitive);check(`${schema.$id}.${f.key} primitive resolves ${f.primitive}`,Boolean(p));if(p&&f.config){const allowed=new Set(p.supportedConfig);for(const cfg of Object.keys(f.config))check(`${schema.$id}.${f.key} config supported ${cfg}`,allowed.has(cfg),f.primitive);if(f.primitive==="fields.relation"&&f.config.relationshipTarget)check(`${schema.$id}.${f.key} relationshipTarget resolves ${f.config.relationshipTarget}`,schemaMap.has(f.config.relationshipTarget)||registry?.items?.some(x=>x.id===f.config.relationshipTarget),f.config.relationshipTarget);}}
     if(f.schema)check(`${schema.$id}.${f.key} nested schema resolves ${f.schema}`,schemaMap.has(f.schema),f.schema);
   }
   const ruleIds=schema.validationRules.map(r=>r.id);check(`${schema.$id} validation IDs unique`,ruleIds.length===new Set(ruleIds).size);schema.validationRules.forEach(r=>check(`${schema.$id} validation described ${r.id}`,typeof r.description==="string"&&r.description.length>0));
   schema.relationships.forEach(r=>{check(`${schema.$id} relationship target ${r.target} resolves`,schemaMap.has(r.target)||fieldMap.has(r.target)||registry?.items?.some(x=>x.id===r.target),r.target);});
 }
 const pub=schemaMap.get("core.publishing");check("Publishing composes visibility",pub?.fields?.some(f=>f.schema==="core.visibility"));check("Publishing composes schedule",pub?.fields?.some(f=>f.schema==="core.scheduleWindow"));check("Publishing uses actor reference",pub?.fields?.some(f=>f.schema==="core.actorReference"));
 const audit=schemaMap.get("core.auditRecord");check("Audit is private by default",audit?.delivery?.publicAllowed===false);check("Audit has noSecrets invariant",audit?.validationRules?.some(r=>r.id==="noSecrets"));
 const media=schemaMap.get("shared.mediaAsset");check("Media is provider-neutral",media?.notes?.some(x=>x.includes("Storage bucket")));check("Media public URL optional",media?.fields?.find(f=>f.key==="publicUrl")?.required===false);
 const link=schemaMap.get("shared.link");check("Link rejects unsafe schemes",link?.validationRules?.some(r=>r.id==="unsafeSchemesRejected"));
 const ext=schemaMap.get("shared.externalReference");check("External metadata forbids secrets",ext?.validationRules?.some(r=>r.id==="metadataNoSecrets"));
}
if(registry&&index){const ids=new Set(registry.items.map(x=>x.id));index.schemas.forEach(s=>check(`Main registry indexes ${s.$id}`,ids.has(s.$id)));check("Main registry has 19 Shared Core schema items",registry.items.filter(x=>x.type==="schema"&&["core","shared"].includes(x.domain)).length===19);check("Shared Core standard indexed",ids.has("core.sharedCoreStandard"));check("No Phase 5+ business schemas fabricated",!registry.items.some(x=>x.phase>=5&&["content","commerce","seo","forms","marketing"].includes(x.domain)&&x.type==="schema"));}
const raw=read("registry/core/index.json"), digest=crypto.createHash("sha256").update(raw).digest("hex"), generated=read("js/generated-core-schemas.js");check("Generated core fallback declares source",generated.includes("Source: registry/core/index.json"));check("Generated core fallback checksum matches",generated.includes(digest),digest);check("Generated core fallback exports data",generated.includes("export const GENERATED_CORE_SCHEMAS ="));
const routes=read("js/routes.js"),router=read("js/router.js"),pages=read("js/pages.js"),html=read("index.html");check("Core route available",routes.includes('path: "/registry/core"')&&routes.includes('phase: 4, status: "available"'));check("Shared route available",routes.includes('path: "/registry/shared"')&&routes.includes('phase: 4, status: "available"'));check("Core explorer renderer exists",pages.includes("renderCoreSchemasIndex"));check("Core detail renderer exists",pages.includes("renderCoreSchemaDetail"));check("Core list binding exists",router.includes("bindCoreList"));check("Core engine loads authoritative index",read("js/core-schema-engine.js").includes('fetch("./registry/core/index.json"'));check("Core engine has generated fallback",read("js/core-schema-engine.js").includes("GENERATED_CORE_SCHEMAS"));check("Core CSS loaded",html.includes('./css/core-schemas.css'));check("Portal version shown",html.includes("v0.5.0"));
if(acceptance){check("Phase 4 acceptance version",acceptance.version===version);check("All Phase 4 acceptance checks passed",acceptance.checks.every(x=>x.passed===true));}
for(const rel of ["js/app.js","js/router.js","js/routes.js","js/pages.js","js/search.js","js/utils.js","js/registry-engine.js","js/generated-registry.js","js/field-registry-engine.js","js/generated-fields.js","js/core-schema-engine.js","js/generated-core-schemas.js","scripts/generate-registry-bootstrap.mjs","scripts/sync-field-registry.mjs","scripts/sync-core-schema-registry.mjs"]){const r=spawnSync(process.execPath,["--check",path.join(root,rel)],{encoding:"utf8"});check(`JavaScript syntax valid: ${rel}`,r.status===0,r.stderr.trim());}
const css=fs.readdirSync(path.join(root,"css")).filter(x=>x.endsWith(".css")).map(x=>read(`css/${x}`)).join("\n").toLowerCase();check("Light-only preserved",!css.includes("prefers-color-scheme: dark"));check("No backdrop-filter",!css.includes("backdrop-filter"));check("No 3D transforms",!css.includes("perspective(")&&!css.includes("rotatex(")&&!css.includes("rotatey("));
console.log("NEXT F Contracts Phase 4 validation");console.log(`Version: ${version}`);console.log(`Shared Core Schemas: ${index?.schemas?.length??0}`);console.log(`Registry items: ${registry?.items?.length??0}`);console.log(`Passes: ${passes.length}`);console.log(`Failures: ${failures.length}`);if(failures.length){console.error("Failures:");failures.forEach(x=>console.error(`- ${x}`));process.exit(1);}console.log("PASS - Phase 4 Shared Core Schemas are internally consistent.");
